;1、域名组
ruleset=🇨🇳 国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🇨🇳 国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
;ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🇨🇳 国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🇨🇳 国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🔍 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list
ruleset=Ⓜ️ Microsoft,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Microsoft/Microsoft.list
ruleset=🍎 Apple,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Apple/Apple.list
ruleset=✈️ Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Telegram/Telegram.list
ruleset=💬 OpenAi,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI.list
ruleset=📹 YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTube/YouTube.list
;ruleset=💙 Amazon,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Amazon/Amazon.list
;ruleset=🏰 Disney,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
ruleset=🍿 Netflix,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
;ruleset=🎭 HBO,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/HBO/HBO.list
ruleset=📱 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list
ruleset=🌍 国外代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
ruleset=🇨🇳 国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🇨🇳 国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🇨🇳 国内直连,https://raw.githubusercontent.com/hzy71366/zayne/refs/heads/main/Clash/list/Direct.list
ruleset=🇨🇳 国内直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

;2、策略组（域名组-节点组）
custom_proxy_group=🌍 国外代理`select`[]DIRECT`[]手动选择1`[]手动选择2`[]自动选择`[]香港自动`[]台湾自动`[]日本自动`[]狮城自动`[]美国自动`[]REJECT
custom_proxy_group=🔍 Google`select`[]DIRECT`[]🌍 国外代理`[]手动选择1`[]手动选择2`[]自动选择`[]香港自动`[]台湾自动`[]日本自动`[]狮城自动`[]美国自动`[]REJECT
custom_proxy_group=💬 OpenAi`select`[]DIRECT`[]🌍 国外代理`[]手动选择1`[]手动选择2`[]自动选择`[]香港自动`[]台湾自动`[]日本自动`[]狮城自动`[]美国自动`[]REJECT
custom_proxy_group=✈️ Telegram`select`[]DIRECT`[]🌍 国外代理`[]手动选择1`[]手动选择2`[]自动选择`[]香港自动`[]台湾自动`[]日本自动`[]狮城自动`[]美国自动`[]REJECT
custom_proxy_group=📹 YouTube`select`[]DIRECT`[]🌍 国外代理`[]手动选择1`[]手动选择2`[]自动选择`[]香港自动`[]台湾自动`[]日本自动`[]狮城自动`[]美国自动`[]REJECT
;custom_proxy_group=💙 Amazon`select`[]DIRECT`[]🌍 国外代理`[]手动选择1`[]手动选择2`[]自动选择`[]香港自动`[]台湾自动`[]日本自动`[]狮城自动`[]美国自动`[]REJECT
;custom_proxy_group=🏰 Disney`select`[]DIRECT`[]🌍 国外代理`[]手动选择1`[]手动选择2`[]自动选择`[]香港自动`[]台湾自动`[]日本自动`[]狮城自动`[]美国自动`[]REJECT
custom_proxy_group=🍿 Netflix`select`[]DIRECT`[]🌍 国外代理`[]手动选择1`[]手动选择2`[]自动选择`[]香港自动`[]台湾自动`[]日本自动`[]狮城自动`[]美国自动`[]REJECT
;custom_proxy_group=🎭 HBO`select`[]DIRECT`[]🌍 国外代理`[]手动选择1`[]手动选择2`[]自动选择`[]香港自动`[]台湾自动`[]日本自动`[]狮城自动`[]美国自动`[]REJECT
custom_proxy_group=📱 TikTok`select`[]DIRECT`[]🌍 国外代理`[]手动选择1`[]手动选择2`[]自动选择`[]香港自动`[]台湾自动`[]日本自动`[]狮城自动`[]美国自动`[]REJECT
custom_proxy_group=Ⓜ️ Microsoft`select`[]DIRECT`[]🌍 国外代理`[]手动选择1`[]手动选择2`[]自动选择`[]香港自动`[]台湾自动`[]日本自动`[]狮城自动`[]美国自动`[]REJECT
custom_proxy_group=🍎 Apple`select`[]DIRECT`[]🌍 国外代理`[]手动选择1`[]手动选择2`[]自动选择`[]香港自动`[]台湾自动`[]日本自动`[]狮城自动`[]美国自动`[]REJECT
;custom_proxy_group=📢 谷歌FCM`select`[]DIRECT`[]🌍 国外代理`[]手动选择1`[]手动选择2`[]自动选择`[]香港自动`[]台湾自动`[]日本自动`[]狮城自动`[]美国自动`[]REJECT
custom_proxy_group=🇨🇳 国内直连`select`[]DIRECT`[]REJECT
custom_proxy_group=🛑 广告拦截`select`[]DIRECT`[]REJECT
custom_proxy_group=🍃 应用净化`select`[]DIRECT`[]REJECT
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🌍 国外代理`[]手动选择1`[]手动选择2`[]自动选择`[]香港自动`[]台湾自动`[]日本自动`[]狮城自动`[]美国自动`[]REJECT

;3、节点组
custom_proxy_group=手动选择1`select`.*
custom_proxy_group=手动选择2`select`.*
custom_proxy_group=自动选择`url-test`.*`http://www.gstatic.com/generate_204`180,5,100
custom_proxy_group=香港自动`url-test`(港|HK|Hong Kong)`http://www.gstatic.com/generate_204`180,5,100
custom_proxy_group=台湾自动`url-test`(台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`180,5,100
custom_proxy_group=日本自动`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)(?!利亚)`http://www.gstatic.com/generate_204`180,5,100
custom_proxy_group=狮城自动`url-test`(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`180,5,100
custom_proxy_group=美国自动`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.gstatic.com/generate_204`180,5,100

;4、启用规则集
enable_rule_generator=true
overwrite_original_rules=true
